#!/usr/bin/env bash
# Configures HAProxy as a load balancer for rb4.com

# Install HAProxy on the load balancer
apt-get -y update
apt-get -y install haproxy

# Configure HAProxy configuration file to distribute requests using a roundrobin algorithm
echo '
frontend shl92_frontend
        bind 0.0.0.0:80
        default_backend shl92_backend

backend shl92_backend
        balance roundrobin
        server 451968-web-01 100.25.144.97:80 check
        server 451968-web-02 154.236.233.31:80 check
' > /etc/haproxy/haproxy.cfg

# Restart HAProxy service
service haproxy restart